[workspace]

members = ["exec01", "lib01"]

resolver = "3"

[workspace.package]
version = "0.1.1"
authors = ["Eduardo Pagotto"]
description = "Just a template to understand workspaces in rust"
documentation = "https://github.com/EduardoPagotto/template-rust"

#[workspace.dependencies]
