[package]
name = "exec01"
version.workspace = true
edition = "2024"
authors.workspace = true
description.workspace = true
documentation.workspace = true


[dependencies]
lib01 = { path = "../lib01" }
