[build]
#target = "x86_64-unknown-linux-gnu"
rustflags = ["-C", "link-dead-code"]

# ref: https://github.com/johnthagen/min-sized-rust
[profile.release]
opt-level = "z"   # Optimize for size.
strip = true      # Automatically strip symbols from the binary.
lto = true        # Link Time Optimization
codegen-units = 1
panic = "abort"
